SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.CurrencyConverterFactory:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "CurrencyConverter"
